name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app -d app_test" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_pgsql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Wait for PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U app; do
            sleep 1
          done

      - name: Run Doctrine migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run PHPUnit
        run: php bin/phpunit
        env:
          DATABASE_URL: postgresql://app:password@localhost:5432/app_test?serverVersion=16

